version: 0.2
env:
  variables:
    SOLUTION: WebApplication1.sln
    DOTNET_FRAMEWORK: 8.0

phases:
  install:
    runtime-versions:
      dotnet: 8.0
      
  pre_build:
    commands:
      - dotnet restore $SOLUTION
      
  build:
    commands:
      - dotnet build $SOLUTION -c Release
      
artifacts:
  files:
    - WebApplication1/bin/Release/net8.0/**/*
    - appspec.yml
  discard-paths: no
