version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 8.0
  pre_build:
    commands:
      - dotnet restore
  build:
    commands:
      - dotnet build -c Release
      - dotnet test -c Release --no-build
  post_build:
    commands:
      - dotnet publish -c Release --no-build -o ./publish_output
artifacts:
  base-directory: ./publish_output
  files:
    - '**/*'
cache:
  paths:
    - '/root/.nuget/**/*'
